TYPE = 'function'

[VALUE]
__closure__ = null
__defaults__ = null
__name__ = 'inc'

[VALUE.__code__]
TYPE = 'code'

[VALUE.__code__.VALUE]
__doc__ = 'code(argcount, posonlyargcount, kwonlyargcount, nlocals, stacksize,
      flags, codestring, constants, names, varnames, filename, name,
      firstlineno, lnotab[, freevars[, cellvars]])

Create a code object.  Not for the faint of heart.'
co_argcount = 1
co_filename = '/home/alcabens/2course/isp/2LR/Test/objects.py'
co_firstlineno = 6
co_flags = 67
co_kwonlyargcount = 0
co_name = 'inc'
co_nlocals = 1
co_posonlyargcount = 0
co_stacksize = 2

[VALUE.__code__.VALUE.co_cellvars]
TYPE = 'tuple'
VALUE = []

[VALUE.__code__.VALUE.co_code]
TYPE = 'bytes'
VALUE = [124, 0, 100, 1, 23, 0, 83, 0]

[VALUE.__code__.VALUE.co_consts]
TYPE = 'tuple'
VALUE = [null, 1]

[VALUE.__code__.VALUE.co_freevars]
TYPE = 'tuple'
VALUE = []

[VALUE.__code__.VALUE.co_lnotab]
TYPE = 'bytes'
VALUE = [0, 1]

[VALUE.__code__.VALUE.co_names]
TYPE = 'tuple'
VALUE = []

[VALUE.__code__.VALUE.co_varnames]
TYPE = 'tuple'
VALUE = ['n']

[VALUE.__globals__]
